
modLoader="javafml"
loaderVersion="[36,41)" # This is typically bumped every Minecraft version by Forge.
license="CC BY-NC-SA 4.0"
issueTrackerURL="${issues}"


[[mods]]
modId = "${mod_id}"
version= "${version}"
displayName = "${mod_name}"
authors = $authors
displayURL = "${homepage}"
description = "${description}"
logoFile = "logo.png"
catalogueImageIcon = "assets/horsebuff/icon.png"
acceptableRemoteVersions="*"
